### ISSUE TITLE
Javascript Error: Jupyter is not defined

### ISSUE THREAD

**Issue by StefanBrand** [n8henrie/jupyter-black#1]
- **Operating system and version**: Ubuntu 20.04.2 LTS
- **Python version**: Python 3.9.7
- **jupyter-black version**: 
 
```
jupyter-black                 0.1.1       /opt/conda/envs/myenv/lib/python3.9/site-packages pip
jupyter-client                7.0.6       /opt/conda/envs/myenv/lib/python3.9/site-packages pip
jupyter-core                  4.9.1       /opt/conda/envs/myenv/lib/python3.9/site-packages pip
jupyterlab-pygments           0.1.2        /opt/conda/envs/myenv/lib/python3.9/site-packages pip
jupyterlab-widgets            1.0.2       /opt/conda/envs/myenv/lib/python3.9/site-packages pip
```
JupyterLab itself is version 3.1.8

## My Issue
I can `%load_ext jupyter_black` fine, but when I execute a cell to be formatted, this error appears as output to the cell where I loaded `jupyter_black`: `Javascript Error: Jupyter is not defined`

## [WHYT](http://mattgemmell.com/what-have-you-tried)

I've tried with `DEBUG`, but there is no additional information:

![image](https://user-images.githubusercontent.com/8948865/140974865-d2d19cc0-50be-4754-8ebb-0be9a5c131d2.png)

When I install `nb_black` _instead of_ `jupyter_black` formatting works:

![image](https://user-images.githubusercontent.com/8948865/140976019-2c7e4737-dcad-4274-b6d2-eb5d51a21697.png)

---

Please make sure you've taken these steps before submitting a new issue:

- [x] Include the Python and jupyter-black version in your issue
- [x] Ensure you're running a supported version of Python
- [x] Run jupyter-black in debug mode if applicable and include
  relevant output
- [x] Search the existing (including closed) issues
- [x] Please use [codeblocks][1] for any code, config, program output, etc.

[1]: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by n8henrie** [comment]
Hi -- thanks for my first issue!

I'm seeing an inconsistency -- 

> JupyterLab itself is version 3.1.8

vs `lab=False` in your screenshot. 

Can you clarify whether you're using Lab or not? If so, you'll need `lab=True`, since lab doesn't have a globally available `Jupyter` in the JS environment.

**Comment by StefanBrand** [comment]
Ha, gotcha! Thanks for replying so quickly. I copy pasted the example from the [README](https://github.com/n8henrie/jupyter-black#configurable-recommended).

It works with `lab=True`. :tada: However, I expected `%load_ext jupyter_black` to work with JupyterLab by default. `nb_black` had two commands to support both notebook and lab:

- `nb_black`
- `lab_black`

I therefore propose an analogous solution, for example:

- `jupyter_black`
- `jupyterlab_black`

**Comment by n8henrie** [comment]
> However, I expected %load_ext jupyter_black to work with JupyterLab by default. 

Great point! I had meant to point this out in the readme, can't believe I forgot! I'm still back and forth about making `lab` the default; I don't have a great sense for what less technical users are using more (since the more technical users will hopefully default to the "configurable" loading).

> I therefore propose an analogous solution

Thanks for the suggestion, but part of the reason I wanted to fork was because this design decision bothered me! I much prefer the kwarg and `jupyter_black.load`.

**Comment by StefanBrand** [comment]
What are the cons of `%load_ext` in your opinion?

**Comment by n8henrie** [comment]
The fact that it's not configurable, and AFAICT there's [no great way](https://github.com/n8henrie/jupyter-black/blob/b1f2d998fdf53ea0376f41ec02d0a8d2874190a0/src/jupyter_black/jupyter_black.py#L130) to automatically detect lab vs notebook, so it will by definition *not* work for one of those two groups (lab users vs notebook users), which will lead to more issues like this one!

Also, the syntax would break a python interpreter, whereas one can `import jupyter_black` and use some logic to *not* run `jupyter_black.load` if not in a jupyter environment (I use this pattern a lot EDIT: \*).

Being 23 characters vs 42 characters (`import jupyter_black; jupyter_black.load()`), an extra 19 characters (that only needs to be written once per notebook) doesn't seem too onerous IMO. ¯\\_(ツ)_/¯

\* the pattern being draft some code in a notebook until I can `restart kernel and run all cells` without error, then download as `.py` and run that file directly -- usually doing this in `screen` or `tmux` because it's a long-running task like training a neural net and I don't want closing the web browser to kill the task).

**Comment by StefanBrand** [comment]
Ok I understand. Thanks for your thorough explanation. It's not a one-liner, btw; `jupyter_black` turns it to: :wink: 

```
import jupyter_black

jupyter_black.load(lab=True)
```

**Comment by n8henrie** [comment]
>  It's not a one-liner, btw

To be fair, you only have to *type* a one-liner 😆
